#ifndef STRUCTURES_H
#define STRUCTURES_H

enum ErrorFlags
{
  ERR_INVALID_ARGS,
  ERR_SYNTAX_TOKEN,
  ERR_SYNTAX_UNKNOWN_FUNCTION,
  ERR_SYNTAX_DATATYPE,
  ERR_SYNTAX_FUNCTION_ARGS,
  ERR_SYNTAX_FUNCTION_RETURN
};

#endif
